<?php

namespace App\Command;

use Doctrine\DBAL\Connection;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(name: 'app:propose-rule-changes', description: 'Review failed/partial outcomes and propose rule modifications')]
class ProposeRuleChangeCommand extends Command
{
    public function __construct(private Connection $db)
    {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addOption('rule', null, InputOption::VALUE_OPTIONAL, 'Propose changes for a specific rule ID only')
            ->addOption('apply', null, InputOption::VALUE_NONE, 'Auto-apply approved proposals to system-prompt.txt');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $ruleFilter = $input->getOption('rule');
        $autoApply  = (bool) $input->getOption('apply');

        $this->ensureSchema();

        $output->writeln('');
        $output->writeln('+============================================+');
        $output->writeln('|     LOGIRI RULE EVOLUTION ENGINE            |');
        $output->writeln('|     Propose changes from outcome data       |');
        $output->writeln('+============================================+');
        $output->writeln('');

        // Pull unapproved proposals from rule_feedback where change_type != 'none'
        $proposals = $this->getPendingProposals($ruleFilter);

        if (empty($proposals)) {
            $output->writeln("No pending rule change proposals found.");
            $output->writeln("  Proposals are generated by app:verify-outcomes when fixes fail.");
            return Command::SUCCESS;
        }

        $output->writeln("Found " . count($proposals) . " pending proposal(s).");
        $output->writeln('');

        // Group proposals by rule_id
        $grouped = [];
        foreach ($proposals as $p) {
            $grouped[$p['rule_id']][] = $p;
        }

        foreach ($grouped as $ruleId => $ruleProposals) {
            $output->writeln("===================================================");
            $output->writeln("  RULE: {$ruleId}");
            $output->writeln("  Proposals: " . count($ruleProposals));
            $output->writeln("===================================================");
            $output->writeln('');

            $failCount    = 0;
            $partialCount = 0;

            foreach ($ruleProposals as $p) {
                if ($p['outcome_status'] === 'FAIL') $failCount++;
                if ($p['outcome_status'] === 'PARTIAL') $partialCount++;

                $output->writeln("  [{$p['outcome_status']}] {$p['url']}");
                $output->writeln("    What didn't work: " . ($p['what_didnt_work'] ?? 'Unknown'));
                $output->writeln("    Proposed: ({$p['change_type']}) " . ($p['proposed_change'] ?? 'None'));
                $output->writeln('');
            }

            // If multiple failures for the same rule, synthesize a single recommendation
            if (count($ruleProposals) >= 2 && ($failCount >= 2 || ($failCount + $partialCount) >= 3)) {
                $output->writeln("  !! PATTERN DETECTED: {$failCount} FAIL + {$partialCount} PARTIAL across " . count($ruleProposals) . " pages");
                $output->writeln("  This rule may need modification, not just better execution.");
                $output->writeln('');

                $synthesis = $this->synthesizeProposal($ruleId, $ruleProposals, $output);

                if ($synthesis) {
                    $output->writeln("  -- SYNTHESIZED PROPOSAL --");
                    $output->writeln("  Change type: {$synthesis['change_type']}");
                    $output->writeln("  Summary: {$synthesis['summary']}");
                    $output->writeln('');
                    $output->writeln("  Proposed new rule text:");
                    $output->writeln("  " . str_replace("\n", "\n  ", $synthesis['new_rule_text']));
                    $output->writeln('');

                    $this->storeSynthesizedProposal($ruleId, $synthesis, $ruleProposals);
                    $this->createReviewTask($ruleId, $synthesis, $ruleProposals, $output);
                }
            } else {
                $output->writeln("  Not enough failures to trigger rule modification.");
                $output->writeln("  Individual follow-up tasks were already created by verify-outcomes.");
            }

            $output->writeln('');
        }

        $output->writeln('==============================================');
        $output->writeln("Reviewed " . count($grouped) . " rule(s) with " . count($proposals) . " proposal(s).");

        return Command::SUCCESS;
    }

    private function getPendingProposals(?string $ruleFilter): array
    {
        try {
            $sql = "SELECT * FROM rule_feedback
                    WHERE change_type != 'none'
                    AND change_approved IS NULL
                    AND outcome_status IN ('FAIL', 'PARTIAL')";

            $params = [];
            if ($ruleFilter) {
                $sql .= " AND rule_id = :rule_id";
                $params['rule_id'] = strtoupper($ruleFilter);
            }

            $sql .= " ORDER BY rule_id, created_at DESC";
            return $this->db->fetchAllAssociative($sql, $params);
        } catch (\Exception $e) {
            return [];
        }
    }

    private function synthesizeProposal(string $ruleId, array $proposals, OutputInterface $output): ?array
    {
        $claudeKey = $_ENV['ANTHROPIC_API_KEY'] ?? '';
        if (!$claudeKey) return null;

        $currentRule = $this->loadCurrentRule($ruleId);
        $proposalCount = count($proposals);

        $proposalContext = "";
        foreach ($proposals as $p) {
            $proposalContext .= "URL: {$p['url']}\n";
            $proposalContext .= "  Outcome: {$p['outcome_status']}\n";
            $proposalContext .= "  What worked: " . ($p['what_worked'] ?? 'Nothing') . "\n";
            $proposalContext .= "  What didn't: " . ($p['what_didnt_work'] ?? 'Unknown') . "\n";
            $proposalContext .= "  Individual proposal: " . ($p['proposed_change'] ?? 'None') . "\n";
            $proposalContext .= "  Change type: {$p['change_type']}\n\n";
        }

        $prompt = <<<PROMPT
You are the Logiri rule evolution engine for Double D Trailers (doubledtrailers.com).

Multiple outcomes for rule {$ruleId} have shown FAIL or PARTIAL results. Analyze the pattern and propose a single concrete modification.

CURRENT RULE:
{$currentRule}

OUTCOME DATA ({$proposalCount} verifications):
{$proposalContext}

AVAILABLE CRAWL FIELDS:
url, http_status, title_tag, h1, h2s, meta_description, word_count, has_central_entity, central_entity_count, internal_links, has_core_link, core_links_found, h1_matches_title, schema_types, canonical_url, is_noindex, page_type, crawled_at, is_utility, internal_link_count, body_text_snippet, first_sentence_text, image_count, last_modified_date, has_faq_section, has_product_image

Respond with EXACTLY this JSON (no markdown, no backticks):
{
  "change_type": "One of: refine_threshold, modify_diagnosis, modify_action, deprecate_rule, split_rule",
  "summary": "1-2 sentence explanation of what should change and why",
  "new_rule_text": "Complete replacement text for this rule in system-prompt.txt format. Include: Rule ID | Name, Trigger Condition (valid SQL using only available fields), Threshold, Diagnosis, Action Output, Priority, Assigned.",
  "rationale": "Why this change should improve outcomes based on the failure patterns"
}

CONSTRAINTS:
- Do NOT change the rule ID
- Trigger SQL must use ONLY the available crawl fields
- Product pages max 500 words, outer pages min 1000 words, max 3 internal links, zero external links
- Use only real DDT terms: Z-Frame, SafeTack, SafeBump, SafeKick
PROMPT;

        try {
            $ch = curl_init('https://api.anthropic.com/v1/messages');
            curl_setopt_array($ch, [
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_POST           => true,
                CURLOPT_POSTFIELDS     => json_encode([
                    'model'      => 'claude-sonnet-4-6',
                    'max_tokens' => 2000,
                    'messages'   => [['role' => 'user', 'content' => $prompt]],
                ]),
                CURLOPT_HTTPHEADER => [
                    'Content-Type: application/json',
                    'x-api-key: ' . $claudeKey,
                    'anthropic-version: 2023-06-01',
                ],
                CURLOPT_TIMEOUT => 90,
            ]);

            $response = curl_exec($ch);
            $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            curl_close($ch);

            if ($httpCode !== 200 || !$response) return null;

            $data = json_decode($response, true);
            $text = $data['content'][0]['text'] ?? '';
            $text = preg_replace('/^```json\s*/', '', $text);
            $text = preg_replace('/\s*```$/', '', $text);

            $parsed = json_decode($text, true);
            if (!$parsed || !isset($parsed['summary'])) return null;

            return $parsed;
        } catch (\Exception $e) {
            $output->writeln("   [WARN] LLM synthesis failed: " . substr($e->getMessage(), 0, 80));
            return null;
        }
    }

    private function loadCurrentRule(string $ruleId): string
    {
        $promptPath = dirname(__DIR__, 2) . '/system-prompt.txt';
        if (!file_exists($promptPath)) return "(Rule not found)";

        $content = file_get_contents($promptPath);
        $escaped = preg_quote($ruleId, '/');
        if (preg_match("/\n{$escaped}\s*\|.*?\n---/s", $content, $match)) {
            return substr(trim($match[0]), 0, 2000);
        }

        return "(Rule {$ruleId} not found in system-prompt.txt)";
    }

    private function storeSynthesizedProposal(string $ruleId, array $synthesis, array $proposals): void
    {
        try {
            $this->db->insert('rule_change_proposals', [
                'rule_id'       => $ruleId,
                'change_type'   => $synthesis['change_type'] ?? 'modify_action',
                'summary'       => $synthesis['summary'] ?? '',
                'new_rule_text' => $synthesis['new_rule_text'] ?? '',
                'rationale'     => $synthesis['rationale'] ?? '',
                'source_count'  => count($proposals),
                'status'        => 'pending',
                'created_at'    => date('Y-m-d H:i:s'),
            ]);
        } catch (\Exception $e) {}
    }

    private function createReviewTask(string $ruleId, array $synthesis, array $proposals, OutputInterface $output): void
    {
        try {
            $assignees = array_unique(array_filter(array_column($proposals, 'assigned_to')));
            $assignee  = !empty($assignees) ? $assignees[0] : null;
            $proposalCount = count($proposals);

            $title = "[RULE-CHANGE] Review proposed modification to {$ruleId}";
            $desc  = "PROPOSED RULE CHANGE\n"
                . "Rule: {$ruleId}\n"
                . "Change type: {$synthesis['change_type']}\n"
                . "Reason: {$synthesis['summary']}\n\n"
                . "Based on {$proposalCount} FAIL/PARTIAL outcome(s).\n\n"
                . "RATIONALE:\n{$synthesis['rationale']}\n\n"
                . "NEW RULE TEXT:\n{$synthesis['new_rule_text']}\n\n"
                . "ACTION REQUIRED:\n"
                . "1. Review the proposed change above\n"
                . "2. If approved: update system-prompt.txt with the new rule text\n"
                . "3. If rejected: mark done with a note explaining why\n"
                . "4. Re-run: php bin/console app:evaluate-rule --rule={$ruleId} --skip-validation";

            $existing = $this->db->fetchAssociative(
                "SELECT id FROM tasks WHERE title LIKE :title AND status != 'done'",
                ['title' => "%RULE-CHANGE%{$ruleId}%"]
            );

            if (!$existing) {
                $this->db->insert('tasks', [
                    'title'           => substr($title, 0, 500),
                    'description'     => $desc,
                    'rule_id'         => $ruleId,
                    'assigned_to'     => $assignee,
                    'status'          => 'pending',
                    'priority'        => 'high',
                    'estimated_hours' => 1,
                    'logged_hours'    => 0,
                    'created_at'      => date('Y-m-d H:i:s'),
                ]);
                $output->writeln("  >> Task created: {$title}");
            }

            try {
                $this->db->insert('activity_log', [
                    'actor'        => 'Logiri',
                    'action'       => 'proposed_rule_change',
                    'target_type'  => 'rule',
                    'target_title' => $ruleId,
                    'details'      => "{$synthesis['change_type']}: {$synthesis['summary']}",
                    'created_at'   => date('Y-m-d H:i:s'),
                ]);
            } catch (\Exception $e) {}
        } catch (\Exception $e) {}
    }

    private function ensureSchema(): void
    {
        try {
            $this->db->executeStatement("
                CREATE TABLE IF NOT EXISTS rule_change_proposals (
                    id              SERIAL PRIMARY KEY,
                    rule_id         VARCHAR(30) NOT NULL,
                    change_type     VARCHAR(30) NOT NULL,
                    summary         TEXT,
                    new_rule_text   TEXT,
                    rationale       TEXT,
                    source_count    INT DEFAULT 0,
                    status          VARCHAR(20) DEFAULT 'pending',
                    approved_by     VARCHAR(100),
                    approved_at     TIMESTAMP,
                    applied_at      TIMESTAMP,
                    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            ");
        } catch (\Exception $e) {}
    }
}